name: nlp_sentiment_analysis_comparison_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.12.0=pyhcf101f3_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=25.1.0=py311haa95532_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - backports.zstd=1.2.0=py311h71c1bcc_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - boltons=25.0.0=py311haa95532_0
  - brotli-python=1.2.0=py311hc5da9e4_1
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.3=py311haa95532_0
  - conda=25.11.1=py311haa95532_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=py311haa95532_1
  - conda-package-streaming=0.12.0=py311haa95532_1
  - cpp-expected=1.3.1=h477610d_0
  - debugpy=1.8.19=py311h5dfdfe8_0
  - decorator=5.2.1=py311haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py311haa95532_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h885b0b7_4
  - fmt=12.0.0=h29169d4_0
  - frozendict=2.4.6=py311h02ab6af_0
  - h11=0.16.0=py311haa95532_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=py311haa95532_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - json5=0.12.1=py311haa95532_0
  - jsonpatch=1.33=py311haa95532_1
  - jsonpointer=3.0.0=py311haa95532_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_1
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_highlight_selected_word=0.2.0=pyhd8ed1ab_1006
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libcurl=8.17.0=h97e0424_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libmamba=2.4.0=h3f46830_1
  - libmambapy=2.4.0=py311hd298240_1
  - libsodium=1.0.20=h83e8143_0
  - libsolv=0.7.35=h8883371_0
  - libssh2=1.11.1=h2addb87_0
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=he774522_2
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-inline=0.2.1=py311haa95532_0
  - menuinst=2.4.2=py311h885b0b7_1
  - mistune=3.1.4=pyhcf101f3_0
  - msgpack-python=1.1.1=py311h5da7b33_0
  - nbclassic=1.3.3=pyhcf101f3_0
  - nbconvert=7.16.6=py311haa95532_0
  - nbconvert-core=7.16.6=py311haa95532_0
  - nbconvert-pandoc=7.16.6=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - notebook-shim=0.2.4=py311haa95532_0
  - openssl=3.6.0=h725018a_0
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandoc=3.8.3=h57928b3_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.5=py311haa95532_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.5.0=py311haa95532_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=py311haa95532_0
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py311h827c3e9_2
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - python_abi=3.11=2_cp311
  - pywin32=311=py311h885b0b7_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - pyzmq=27.1.0=py311h7149c55_1
  - referencing=0.37.0=py311haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.30.0=py311hf51aa87_0
  - ruamel.yaml=0.18.16=py311hb9a58be_0
  - ruamel.yaml.clib=0.2.14=py311hb9a58be_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=py311haa95532_0
  - simdjson=4.2.4=h49e36cd_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.1=py311haa95532_0
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - terminado=0.18.1=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h02ab6af_0
  - tqdm=4.67.1=py311h4442805_1
  - traitlets=5.14.3=py311haa95532_0
  - truststore=0.10.1=py311haa95532_1
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - winpty=0.4.3=4
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.24.0=py311he335c29_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - arrow==1.4.0
      - astunparse==1.6.3
      - blis==1.3.3
      - catalogue==2.0.10
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.3
      - cycler==0.12.1
      - cymem==2.0.13
      - en-core-web-sm==3.8.0
      - filelock==3.20.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2025.12.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - ipykernel==7.1.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - joblib==1.5.3
      - jupyter==1.1.1
      - jupyter-client==8.7.0
      - jupyter-console==6.6.3
      - jupyter-contrib-core==0.4.2
      - jupyter-nbextensions-configurator==0.6.4
      - jupyterlab-widgets==3.0.16
      - keras==3.13.0
      - keras-tuner==1.4.8
      - kiwisolver==1.4.9
      - kt-legacy==1.0.5
      - lark==1.3.1
      - libclang==18.1.1
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - namex==0.1.0
      - nbclient==0.10.3
      - networkx==3.6.1
      - nltk==3.9.2
      - notebook==6.4.12
      - numpy==2.4.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - pillow==12.0.0
      - preshed==3.0.12
      - protobuf==6.33.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pytz==2025.2
      - pywinpty==3.0.2
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - regex==2025.11.3
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - smart-open==7.5.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - transformers==4.57.3
      - typer-slim==0.20.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - uv==0.9.18
      - wasabi==1.1.3
      - weasel==0.4.3
      - webcolors==25.10.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1